# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e76d6b52bb0fdb02bd30cfd8489a083b8da3f50e736fab2aaceeba16ae88fc2d0c49ff0b2a937689f1c1157e09570f044e44ca821fc5a3f0a763268798fae37d

test:
  secret_key_base: 7c119a585f6000ffab489cf0d5f8da0973ae69f9db5b811cd1f553a00767acbac23e1f6c249e791229214ae7f948ed3b14fd5f1400471aa5b8ab1dec8ec05a32

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
